config/routes.rb
Rails.application.routes.draw do
  get 'product/:id', to: 'product#show', as: 'product', id: /\d+/

  get 'product/edit'

  get 'search_results' => 'product#search_results', as: 'search_results'

  get 'category/:id', to: 'category#show', as: 'category', id: /\d+/

  get 'products', to: 'home#index'
  get 'home', to: 'home#index'
  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, :description, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name, :description, :price, :stock_quantity, :category_id, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @products = Product.where(category_id: @category)
    @products = Kaminari.paginate_array(@products).page(params[:page]).per(8)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.order(:name)
    @products = Kaminari.paginate_array(@products).page(params[:page]).per(8)
    @categories = Category.all
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def show
    @categories = Category.all
    @product = Product.find(params[:id])
  end

  def edit
  end

  def search_results
    wildcard_keywords = '%' + params[:search_keywords] + '%'
    @products = Product.where("name LIKE ? OR description LIKE ?", wildcard_keywords, wildcard_keywords)
    @categories = Category.all
    @products = Kaminari.paginate_array(@products).page(params[:page]).per(8)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/category/show.html.erb
<%= render partial: 'common/search-bar' %>
<%= render partial: 'common/page-heading', locals: {:heading=> @category.name} %>
<%= render partial: 'common/product-listing'%>

app/views/common/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("banner4.jpg") %>
    </div>

    <div class="item">
      <%= image_tag("banner5.jpg") %>
    </div>

    <div class="item">
      <%= image_tag("banner6.jpg") %>
    </div>

    <div class="item">
      <%= image_tag("banner7.jpg") %>
    </div>

    <div class="item">
      <%= image_tag("banner8.jpg") %>
    </div>

    <div class="item">
      <%= image_tag("banner9.jpg") %>
    </div>
  </div>
</div>

app/views/common/_categories.html.erb
<div class="col-sm-2">
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Sort By Category
    <span class="caret"></span></button>
    <ul class="dropdown-menu dropdown-menu-righ">
      <% @categories.each do |category| %>
        <li><%= link_to category.name, category%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/common/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <a class="navbar-brand" href="/">
      PickYourParts
    </a>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <li><a href="/">Home</a></li>
        <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Parts
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% @categories.each do |category| %>
            <li><%= link_to category.name, category%></li>
          <% end %>
        </ul>
      </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- IF STATEMENT (IF NOT LOGGED IN)-->
        <li><button type="button" class="btn btn-default">Log In</button></li>
        <li><a href="#">Sign Up</a></li>
        <!-- ELSE SHOW PROFILE OR SOMETHING -->
      </ul>
    </div>
  </div>
</nav>

app/views/common/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        PickYourParts
      </a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <li><a href="/">Home</a></li>
        <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Parts
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% @categories.each do |category| %>
            <li><%= link_to category.name, category%></li>
          <% end %>
        </ul>
      </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- IF STATEMENT (IF NOT LOGGED IN)-->
        <li><button type="button" class="btn btn-default">Log In</button></li>
        <li><a href="#">Sign Up</a></li>
        <!-- ELSE SHOW PROFILE OR SOMETHING -->
      </ul>
    </div>
  </div>
</nav>

app/views/common/_page-heading.html.erb
<div class="col-sm-9">
  <h3><%= heading %></h3>
</div>

app/views/common/_product-listing.html.erb
<div class="col-sm-12">
  <% @products.each_slice(4) do |products| %>
    <div class="row">
      <% products.each do |product| %>
        <div class="col-sm-3">
          <div class="product-container">
            <%= image_tag product.image%>
            <div class="product-info">
              <p class="name"><%= link_to product.name, product%></p>
              <h4>$<%= product.price %></h4>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="col-sm-12 text-center">
    <%= paginate @products, theme: 'twitter-bootstrap-4' %>
  </div>
</div>

app/views/common/_search-bar.html.erb
<div class="search-bar">
  <%= render partial: 'common/search' %>
  <%= render partial: 'common/categories', locals: {categories: @categories} %>
</div>

app/views/common/_search.html.erb
<div class="col-sm-4">
  <%= form_tag search_results_path, method: :get do %>
    <div class="input-group">
      <input id="search_keywords" name="search_keywords" type="text" class="form-control" placeholder="Search">
      <div class="input-group-btn">
        <button class="btn btn-default" type="submit">
          <i class="glyphicon glyphicon-search"></i>
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<%= render partial: 'common/search-bar' %>
<%= render partial: 'common/page-heading', locals: {:heading=> "All Products"} %>
<%= render partial: 'common/product-listing'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pick Your Parts! yes</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/navigation' %>
    <%= render partial: 'common/carousel' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/product/edit.html.erb
<h1>Product#edit</h1>
<p>Find me in app/views/product/edit.html.erb</p>

app/views/product/search_results.html.erb
<%= render partial: 'common/search-bar' %>
<%= render partial: 'common/page-heading', locals: {:heading=> "Search Results"} %>
<% if @products.size.zero? %>
  <div class="col-sm-12">
    <p>No products found</p>
  </div>
<% else %>
  <%= render partial: 'common/product-listing'%>
<% end %>

app/views/product/show.html.erb
<div class="col-sm-6">
  <%= image_tag @product.image%>
</div>
<div class="col-sm-6">
  <h1 style="font-weight:bold;"><%= @product.name %></h1>
  <h1 style="margin-top:0px;"><%= @product.price %></h1>
  <p><%= @product.description %></p>
  <button type="button" class="btn btn-default">Add to Cart</button>
</div>